SET search_path TO e_card,public;

CREATE TABLE
    tenants_type (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        name varchar(50) NOT NULL,
        deleted bool DEFAULT false NOT NULL,
        deleted_on timestamptz DEFAULT current_timestamp,
        deleted_by varchar(200),
        CONSTRAINT pk_tenants_type_id PRIMARY KEY (id)
    );
