-- ============================================
-- MIGRACIÓN: Card Contact Info
-- ============================================
SET search_path TO e_card, public;

-- Tabla: card_contact_info
CREATE TABLE e_card.card_contact_info (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    card_id integer NOT NULL,
    contact_type varchar(20) NOT NULL,
    label varchar(50),
    value varchar(300) NOT NULL,
    is_primary bool DEFAULT false,
    display_order integer DEFAULT 0,
    created_on timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_on timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    modified_by integer,
    deleted bool NOT NULL DEFAULT false,
    deleted_on timestamptz DEFAULT CURRENT_TIMESTAMP,
    deleted_by varchar(200),
    CONSTRAINT pk_card_contact_info_id PRIMARY KEY (id),
    CONSTRAINT fk_card_contact_info_card_id FOREIGN KEY (card_id)
        REFERENCES e_card.cards(id) ON DELETE CASCADE,
    CONSTRAINT chk_contact_info_type CHECK (
        contact_type IN ('phone', 'email', 'address', 'website')
    )
);

-- Índices
CREATE INDEX idx_card_contact_info_card_id ON e_card.card_contact_info (card_id);
CREATE INDEX idx_card_contact_info_type ON e_card.card_contact_info (contact_type);

-- Triggers
CREATE TRIGGER mdt_card_contact_info
BEFORE UPDATE ON e_card.card_contact_info
FOR EACH ROW EXECUTE PROCEDURE public.moddatetime();

CREATE TRIGGER card_contact_info_audit_trigger
AFTER INSERT OR UPDATE OR DELETE ON e_card.card_contact_info
FOR EACH ROW EXECUTE PROCEDURE logs.audit_trigger('APPLICATION_LOGS');
