-- ============================================
-- MIGRACIÓN: Card Styles
-- ============================================
SET search_path TO e_card, public;

-- Tabla: card_styles
CREATE TABLE e_card.card_styles (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    card_id integer NOT NULL,
    primary_color varchar(7) DEFAULT '#007bff',
    secondary_color varchar(7) DEFAULT '#6c757d',
    background_color varchar(7) DEFAULT '#ffffff',
    text_color varchar(7) DEFAULT '#212529',
    accent_color varchar(7) DEFAULT '#28a745',
    font_family varchar(50) DEFAULT 'Inter',
    font_size varchar(20) DEFAULT 'medium',
    layout_template varchar(50) DEFAULT 'modern',
    border_radius varchar(20) DEFAULT 'medium',
    background_image_url varchar(255) DEFAULT NULL,
    created_on timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_on timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    modified_by integer,
    deleted bool NOT NULL DEFAULT false,
    deleted_on timestamptz DEFAULT CURRENT_TIMESTAMP,
    deleted_by varchar(200),
    CONSTRAINT pk_card_styles_id PRIMARY KEY (id),
    CONSTRAINT uk_card_styles_card_id UNIQUE (card_id),
    CONSTRAINT fk_card_styles_card_id FOREIGN KEY (card_id)
        REFERENCES e_card.cards(id) ON DELETE CASCADE,
    CONSTRAINT chk_card_styles_colors CHECK (
        primary_color ~ '^#[0-9A-Fa-f]{6}$' AND
        secondary_color ~ '^#[0-9A-Fa-f]{6}$' AND
        background_color ~ '^#[0-9A-Fa-f]{6}$' AND
        text_color ~ '^#[0-9A-Fa-f]{6}$'
    )
);

-- Índices
CREATE INDEX idx_card_styles_card_id ON e_card.card_styles (card_id);

-- Triggers
CREATE TRIGGER mdt_card_styles
BEFORE UPDATE ON e_card.card_styles
FOR EACH ROW EXECUTE PROCEDURE public.moddatetime();

CREATE TRIGGER card_styles_audit_trigger
AFTER INSERT OR UPDATE OR DELETE ON e_card.card_styles
FOR EACH ROW EXECUTE PROCEDURE logs.audit_trigger('APPLICATION_LOGS');
