-- ============================================
-- MIGRACIÓN: Social Network Types
-- ============================================
SET search_path TO e_card, public;

-- Tabla: social_network_types
CREATE TABLE e_card.social_network_types (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    icon_class varchar(100),
    url_pattern varchar(200),
    placeholder_text varchar(100),
    input_type varchar(20) DEFAULT 'text',
    is_active bool NOT NULL DEFAULT true,
    created_on timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_on timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    modified_by integer,
    deleted bool NOT NULL DEFAULT false,
    deleted_on timestamptz DEFAULT CURRENT_TIMESTAMP,
    deleted_by varchar(200),
    CONSTRAINT pk_social_network_types_id PRIMARY KEY (id)
);

-- Trigger para actualización automática
CREATE TRIGGER mdt_social_network_types
BEFORE UPDATE ON e_card.social_network_types
FOR EACH ROW EXECUTE PROCEDURE public.moddatetime();

-- Trigger para auditoría
CREATE TRIGGER social_network_types_audit_trigger
AFTER INSERT OR UPDATE OR DELETE ON e_card.social_network_types
FOR EACH ROW EXECUTE PROCEDURE logs.audit_trigger('APPLICATION_LOGS');

-- Datos iniciales
INSERT INTO e_card.social_network_types (name, icon_class, url_pattern, placeholder_text, input_type, is_active) VALUES
('WhatsApp', 'pi pi-whatsapp', 'https://wa.me/{value}', 'Número con código de país (ej: 5218112345678)', 'tel', true),
('Facebook', 'pi pi-facebook', 'https://facebook.com/{value}', 'Usuario de Facebook', 'text', true),
('Instagram', 'pi pi-instagram', 'https://instagram.com/{value}', 'Usuario de Instagram', 'text', true),
('TikTok', 'pi pi-tiktok', 'https://tiktok.com/@{value}', 'Usuario de TikTok', 'text', true),
('LinkedIn', 'pi pi-linkedin', 'https://linkedin.com/in/{value}', 'Usuario de LinkedIn', 'text', true),
('Twitter/X', 'pi pi-twitter', 'https://twitter.com/{value}', 'Usuario de Twitter/X', 'text', true),
('YouTube', 'pi pi-youtube', 'https://youtube.com/@{value}', 'Canal de YouTube', 'text', true),
('Email', 'pi pi-envelope', 'mailto:{value}', 'Correo electrónico', 'email', true),
('Telegram', 'pi pi-telegram', 'https://t.me/{value}', 'Usuario de Telegram', 'text', true),
('Pinterest', 'pi pi-pinterest', 'https://pinterest.com/{value}', 'Usuario de Pinterest', 'text', true),
('GitHub', 'pi pi-github', 'https://github.com/{value}', 'Usuario de GitHub', 'text', true);
