-- ============================================
-- MIGRACIÓN: Card Views (Analytics)
-- ============================================
SET search_path TO e_card, public;

-- Tabla: card_views
CREATE TABLE e_card.card_views (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    card_id integer NOT NULL,
    viewer_ip inet,
    user_agent text,
    referrer varchar(500),
    country varchar(100),
    city varchar(100),
    device_type varchar(20) CHECK (device_type IN ('mobile', 'desktop', 'tablet')),
    viewed_at timestamptz DEFAULT now(),
    created_on timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_on timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    modified_by integer,
    deleted bool NOT NULL DEFAULT false,
    deleted_on timestamptz DEFAULT CURRENT_TIMESTAMP,
    deleted_by varchar(200),
    CONSTRAINT pk_card_views_id PRIMARY KEY (id),
    CONSTRAINT fk_card_views_card_id FOREIGN KEY (card_id)
        REFERENCES e_card.cards(id) ON DELETE CASCADE
);

-- Índices
CREATE INDEX idx_card_views_card_id ON e_card.card_views (card_id);
CREATE INDEX idx_card_views_date ON e_card.card_views (viewed_at);
CREATE INDEX idx_card_views_ip ON e_card.card_views (viewer_ip);

-- Triggers
CREATE TRIGGER mdt_card_views
BEFORE UPDATE ON e_card.card_views
FOR EACH ROW EXECUTE PROCEDURE public.moddatetime();
