-- ============================================
-- MIGRACIÓN: Card Business Hours
-- ============================================
SET search_path TO e_card, public;

-- Tabla: card_business_hours
CREATE TABLE e_card.card_business_hours (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    card_id integer NOT NULL,
    day_of_week integer NOT NULL,
    open_time time,
    close_time time,
    is_closed bool DEFAULT false,
    notes varchar(200),
    created_on timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_on timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    modified_by integer,
    deleted bool NOT NULL DEFAULT false,
    deleted_on timestamptz DEFAULT CURRENT_TIMESTAMP,
    deleted_by varchar(200),
    CONSTRAINT pk_card_business_hours_id PRIMARY KEY (id),
    CONSTRAINT fk_card_business_hours_card_id FOREIGN KEY (card_id)
        REFERENCES e_card.cards(id) ON DELETE CASCADE,
    CONSTRAINT chk_business_hours_day_of_week CHECK (
        day_of_week >= 0 AND day_of_week <= 6
    )
);

-- Índices
CREATE INDEX idx_card_business_hours_card_id ON e_card.card_business_hours (card_id);
CREATE INDEX idx_card_business_hours_day ON e_card.card_business_hours (day_of_week);

-- Triggers
CREATE TRIGGER mdt_card_business_hours
BEFORE UPDATE ON e_card.card_business_hours
FOR EACH ROW EXECUTE PROCEDURE public.moddatetime();

CREATE TRIGGER card_business_hours_audit_trigger
AFTER INSERT OR UPDATE OR DELETE ON e_card.card_business_hours
FOR EACH ROW EXECUTE PROCEDURE logs.audit_trigger('APPLICATION_LOGS');
