export const enum PermissionKey {
    ViewOwnUser = 'ViewOwnUser',
    ViewAnyUser = 'ViewAnyUser',
    ViewTenantUser = 'ViewTenantUser',
    CreateAnyUser = 'CreateAnyUser',
    CreateTenantUser = 'CreateTenantUser',
    UpdateOwnUser = 'UpdateOwnUser',
    UpdateTenantUser = 'UpdateTenantUser',
    UpdateAnyUser = 'UpdateAnyUser',
    DeleteTenantUser = 'DeleteTenantUser',
    DeleteAnyUser = 'DeleteAnyUser',

    ViewTenant = 'ViewTenant',
    CreateTenant = 'CreateTenant',
    UpdateTenant = 'UpdateTenant',
    DeleteTenant = 'DeleteTenant',

    ViewRole = 'ViewRole',
    CreateRole = 'CreateRole',
    UpdateRole = 'UpdateRole',
    DeleteRole = 'DeleteRole',

    ViewAudit = 'ViewAudit',
    CreateAudit = 'CreateAudit',
    UpdateAudit = 'UpdateAudit',
    DeleteAudit = 'DeleteAudit',

    CreateCard = 'CreateCard',
    ViewOwnCard = 'ViewOwnCard',
    ViewAnyCard = 'ViewAnyCard',
    UpdateOwnCard = 'UpdateOwnCard',
    UpdateAnyCard = 'UpdateAnyCard',
    DeleteOwnCard = 'DeleteOwnCard',
    DeleteAnyCard = 'DeleteAnyCard',
    ViewCardStats = 'ViewCardStats',
    DuplicateCard = 'DuplicateCard',

    ManageCardStyles = 'ManageCardStyles',
    ViewCardAnalytics = 'ViewCardAnalytics',
    ExportCardData = 'ExportCardData',
}
